#CHANNEL_NAME
#ORDERER_ADDR
#ORDERER_PORT

function main {

    set -e

    #ORDERER_PORT_ARGS="-o $ORDERER_ADDR:$ORDERER_PORT --tls --cafile $CA_CHAINFILE --clientauth"
    #ORDERER_CONN_ARGS="$ORDERER_PORT_ARGS --keyfile $CORE_PEER_TLS_CLIENTKEY_FILE --certfile $CORE_PEER_TLS_CLIENTCERT_FILE"
    ORDERER_PORT_ARGS="-o $ORDERER_ADDR:$ORDERER_PORT"
    ORDERER_CONN_ARGS="$ORDERER_PORT_ARGS"

    local CONFIG_BLOCK_PB=$CLI_HOME/config_block.pb
    peer channel fetch config $CONFIG_BLOCK_PB  -c $CHANNEL_NAME $ORDERER_CONN_ARGS

}
main
